name: Deploy DistriPro API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages"

      - name: 'Zip artifact for deployment'
        run: zip -r release.zip .

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        with:
          app-name: 'DistriProAPI'
          package: release.zip
          # IMPORTANT: We are moving away from publish-profile
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
